# It seems GitHub Pages has Jekyll SEO enabled.
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

title: Rustの日本語ドキュメント/Japanese Docs for Rust
description: Rust（プログラミング言語）の日本語文書・和訳文書、日本語コミュニティ紹介
url: https://doc.rust-jp.rs/
lang: ja_JP
